# This workflow creates a GitHub release and attaches the nuget package.
name: Create GitHub Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
  

env:
  PROJECT_PATH: src/SqlCdc/SqlCdc.csproj
  TEST_PROJECT_PATH: tests/SqlCdc.Tests/SqlCdc.Tests.csproj
  
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore
      
      - name: Test
        run: dotnet test ${{ env.TEST_PROJECT_PATH }} -c Release --no-build --verbosity normal

      - name: Pack
        run: dotnet pack ${{ env.PROJECT_PATH }} --configuration Release --no-build -o ./artifacts      

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/*.nupkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release Symbols
        id: create_release_symbols
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/*.snupkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
